### PR TITLE
Pass network as optional parameter

### PR DESCRIPTION
**Pull request by Czino**
For improved testability and enabling me to develop using regtest, I need to be able to pass the network into the verify method.
This is already the case for signing.

### CODE REVIEW

**Comment by ACken2** [comment]
Thanks for the pull request. Based on the files changed, it seems like the main objective is to enable BIP137 and BIP322 signature verification for regtest addresses. Is that correct?

**Comment by Czino** [comment]
Yes, enabling it for regtest and possibly making it compatible with other networks in future such as the liquid network.

**Comment by ACken2** [comment]
Is there any reason why the network cannot be inferred from the address given, but have to be exposed directly?

**Comment by Czino** [comment]
> Is there any reason why the network cannot be inferred from the address given, but have to be exposed directly?

Yes, I can think of 2 reasons:
- adhering to DRY principles: no need to rebuild the address for every network (adding regtest here would mean to extend the return value of `convertPubKeyIntoAddress` by `regtest`)
- more importantly: if you are running the code in a mainnet environment, one does not necessarily want to accidentally validate testnet addresses

**Comment by ACken2** [comment]
> > Is there any reason why the network cannot be inferred from the address given, but have to be exposed directly?
> 
> Yes, I can think of 2 reasons:
> 
> * adhering to DRY principles: no need to rebuild the address for every network (adding regtest here would mean to extend the return value of `convertPubKeyIntoAddress` by `regtest`)
> * more importantly: if you are running the code in a mainnet environment, one does not necessarily want to accidentally validate testnet addresses

As far as I know, signature that is valid for a mainnet address is equally valid for its testnet equivalence, and vice versa. By not wanting to "accidentally validate testnet addresses", do you mean you don't want to accidentally pass a testnet address into the verifySignature method when you only want to validate mainnet addresses?

**Comment by Czino** [comment]
> do you mean you don't want to accidentally pass a testnet address into the verifySignature method when you only want to validate mainnet addresses?

Yes, it's also the standard behaviour of bitcoin core, when an address is provided that is not for the same network. `Invalid address` is returned.

**Comment by ACken2** [comment]
> > do you mean you don't want to accidentally pass a testnet address into the verifySignature method when you only want to validate mainnet addresses?
> 
> Yes, it's also the standard behaviour of bitcoin core, when an address is provided that is not for the same network. `Invalid address` is returned.

I am still doubtful about this particular use case.

The signature itself is network-neural, and it is valid for all addresses that can be derived based on the corresponding public key. Other libraries such as the widely used [bitcoinjs-message](https://www.npmjs.com/package/bitcoinjs-message) also does not impose such limit on the network - the same signature would verify as `true` for both mainnet and testnet address without additional configuration.

The problem of "accidentally passing in a testnet address" sounds like a user-input validation problem, rather than an issue that must be dealt with in this library.

While this could be a useful feature to restrict signature verification on a specific network, I am doubtful on whether it should be mandatory. In my opinion, it is better to infer the network automatically, but allow the option to restrict to a particular network type (as a bonus feature).

**Comment by Czino** [comment]
I changed the code so the network is inferred at the beginning of the verification routine.

Therefore the scope of the PR changed to
- support regtest addresses
- refactoring

**Comment by Keegan-lee** [comment]
When is this PR getting merged?

**Comment by ACken2** [comment]
Sorry, but I currently do not have the time to review this pull request in details. This may get merged in late April or early May.

**Comment by ACken2** [comment]
Closing in favor of pull request #10.

Thank you for your contribution.

**Pull request closed without merging**
